name: sprinkle-env

channels:
  - defaults

dependencies:
  - pip=22.3.1
  - python=3.10.8

  - pip:
      - docpie==0.4.3
      - prompt-toolkit==3.0.36
      - varname==0.10.0
      - tabulate==0.9.0
      - pipreqs==0.4.11
