sprinkle_project_dir = ".sprinkle"
sprinkle_project_settings_file = "settings.pkl"
sprinkle_project_settings_export_file = "sprinkle-job-export.sh"
sprinkle_project_output_dir = sprinkle_project_dir + "/output"
sprinkle_project_log_dir = sprinkle_project_dir + "/log"
sprinkle_project_error_dir = sprinkle_project_dir + "/error"
sprinkle_env_file_name = "environment.yml"
sprinkle_req_file_name = "requirements.txt"